### ISSUE TITLE
Smart Shots - still a few minor blockers

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/solodevguide#88]
http://dev.3dr.com/concept-smartshot.html

OK, so this is much better for release in that it clearly states that it doesn't pretend to say very much. I still think it might be improved for launch.

1. 
   
   >"Smart Shots consist of several functions that provide a high-level interface for controlling the drone."  
   * This isn't really sufficient because it doesn't really explain what a Smartshot is, and only a little about the interface. How about: 
   * 

      > "[Smart shots](http://3drobotics.com/smart-shots/) allow you to pre-program complicated flight paths, enabling users to concentrate on *when to take the shot* rather than *how to fly the vehicle*. 

      > The Smart Shot framework builds upon DroneKit, and adds support to pause and resume shots (storing the flight state) and re-map controller buttons and sticks during a shot.

      >  The most important functions in the `solo.smartshot`are:

1. 
   
   >Handling RC input. Remapping the control sticks to do alternate functions is used, for example, in Cable Cam to allow the right stick to be

   * This sentence ends prematurely.

1. 
   
   >Resume from brake. When the pause button is pressed, the drone goes into BRAKE mode and the flight state is lost. This function is called shortly afterward to restore the flight state and prepare the shot to continue.

   * The second sentence is confusing. "This function is called shortly afterward" sounds like it is called shortly after the pause button is pressed, but wouldn't that be up to the user? I would have thought "This function is called shortly before resuming". Of course it could be correct!
   * I also wonder how the flight state got stored in the first place?

**Comment by tcr3dr** [comment]
Fixed most of these in a straightforward way. Open to further issues on this topic.

**Comment by hamishwillee** [comment]
Nice. I did minor mod https://github.com/3drobotics/solodevguide/commit/be34f95b8fa279bf58bb0bbb05796c20880efb4f to improve the text and fix a spacing bug.

I still don't really understand "resume from BRAKE mode". To be more precise, I understand what you say it does, but I don't know what that would mean in practice. I'm envisaging that you were in guided mode doing "stuff", someone pressed pause to put into BRAKE mode. After 5 seconds you switch back into "GUIDED mode" and do any prep needed to start a new action - I guess in the case of a flip shot, this would be "nothing". I'm assuming when you shove back into guided mode the copter just loiters in place waiting for the next code to run.

Anyway, probably fine for now - something you'd expand on with a real example.
